obj-y	+= cpu.o
obj-y	+= cpufeature.o
obj-y	+= irq.o
obj-y	+= process.o
obj-y	+= ptrace.o
obj-y	+= reset.o
obj-y	+= setup.o
obj-y	+= signal.o
obj-y	+= time.o
obj-y	+= traps.o
obj-y	+= stacktrace.o
obj-y	+= misc.o
obj-y	+= sys.o
obj-y	+= uio.o stdio/
# obj-y := ctx_sw.o intc.o

# these should be removed
# obj-${CONFIG_WASM32_WEB_KBD} += kbd.o
# obj-y += evt.o uio.o syscall.o stdio/
ccflags-y += -Wno-strict-prototypes
