# SPDX-License-Identifier: GPL-2.0-only
mxc_arm-$(CONFIG_ARM) := soc-imx.o
obj-$(CONFIG_ARCH_MXC) += ${mxc_arm-y}
obj-$(CONFIG_HAVE_IMX_GPC) += gpc.o
obj-$(CONFIG_IMX_GPCV2_PM_DOMAINS) += gpcv2.o
obj-$(CONFIG_SOC_IMX8M) += soc-imx8m.o
obj-$(CONFIG_IMX_SCU_SOC) += soc-imx-scu.o
